name: appflowy
version: 0.4.8
adopt-info: appflowy
website: https://appflowy.io
contact: support@appflowy.io
issues: https://github.com/AppFlowy-IO/AppFlowy/issues
source-code: https://github.com/AppFlowy-IO/AppFlowy
icon: snap/gui/icon.svg
confinement: strict
base: core22
grade: stable
license: AGPL-3.0
architectures:
  - build-on: amd64

apps:
  appflowy:
    command: usr/lib/AppFlowy/AppFlowy
    extensions: [gnome]
    desktop: usr/share/applications/AppFlowy.desktop
    common-id: io.appflowy.AppFlowy
    plugs:
      - network
      - network-manager-observe
      - home
      - removable-media

slots:
  dbus-appflowy:
    interface: dbus
    bus: session
    name: io.appflowy.appflowy

parts:
  appflowy:
    plugin: dump
    source: https://github.com/AppFlowy-IO/AppFlowy/releases/download/$SNAPCRAFT_PROJECT_VERSION/AppFlowy-$SNAPCRAFT_PROJECT_VERSION-linux-x86_64.deb
    parse-info: [usr/share/appdata/io.appflowy.AppFlowy.appdata.xml]
    build-packages:
      - wget
      - dpkg
      - libnotify-dev
    override-pull: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_SRC/usr/share/appdata
      wget -O $SNAPCRAFT_PART_SRC/usr/share/appdata/io.appflowy.AppFlowy.appdata.xml https://raw.githubusercontent.com/flathub/io.appflowy.AppFlowy/master/io.appflowy.AppFlowy.appdata.xml
    prime:
      - usr/share/applications
      - usr/share/icons
      - usr/share/metainfo
      - usr/share/appdata
      - usr/lib/

  deps:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
    stage-packages:
      - libkeybinder-3.0-0
    prime:
      - usr/lib/*/libkeybinder*so.*
      - usr/lib/*/libcrypto.so.*
      - usr/lib/*/libssl.so.*
